# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: xenial
language: python
python:
  - "3.6"

cache:
  pip: true

env:
  - DEPLOY_PYPI="true"

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/bundles/*"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  - provider: pypi
    user: fourstix
    password:
      secure: VPXLa3UQxkO5T/w2Z9G2HhYlEN/CHem0zFQPd/0z1ONVGc577bI8865q5iM6oWnYUwAYSLIUZDSdmv6kOau0pZ5ZEfMe6ZAJGAylRYBC5cnLQ4CqvcshIfdWYQtV7ZuM6Uzcft374l8gHEnR1UCZjBT9QesOtBfVIbCZx0f5v4dZuTsslIMOCixKoqXGAoVTsrZ0Mw6fPNW/jvq65Zt1LVr+7ZcBxVSb62W7cWUDEEEuis3ykEUHJOCSoR2JqrrZYhYSf7Nrp484hLTafSHlfbKGQ/TnlJewUNysyv7uqGxmszMXTh2/tAvfafzw126BaH451H5pf9eFx5tU3t+l/R75SYMPTXkEU+V66AH55f6QO0H4dYFWv3FeE7gvM+hS9DlPH2DOwLln3DRGjAdSwH0veYvdJb5VA5Nl082DyNijECHrNd1JrCEQweYtOJ/3TjBl9SBDsoL4BNug6bZKRjngtxxZtMhb7IWRigQ1V3naPi6vrA2CCXvBQsUPcn5OHCEP9m5nPn1pSdpBQ4GoaxQiwJ1fR4c8O1rrqr8ANJ0UajLSCzFN8t75vXV625uiCIw87awrI4lAdqgabEoAo6IYCjSb2iFUZ2bM+Fs3RuKJ7JDmkgbP8kDSaA3oJHscvrrjqlAjGHE+bmU5QBVXHCCNmJluAJGPrSicaaHG8Sw=
    on:
      tags: true
      condition: $DEPLOY_PYPI = "true"

install:
  - pip install -r requirements.txt
  - pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
  - pip install --force-reinstall pylint==1.9.2

script:
  - pylint sparkfun_qwiickeypad.py
  - ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
  - circuitpython-build-bundles --filename_prefix sparkfun-circuitpython-qwiickeypad --library_location .
  - cd docs && sphinx-build -E -W -b html . _build/html && cd ..
